language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - jruby-head
  - ruby-head

sudo: false

script: bundle exec rake $TASK

env:
  - TASK=yaks:rspec
  - TASK=yaks-html:rspec

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: TASK=mutant
  fast_finish: true
  include:
    - rvm: rbx
      env: TASK="yaks:rspec --trace"
    - rvm: rbx
      env: TASK="yaks-html:rspec --trace"
    - rvm: 2.2
      env: TASK=ataru
    - rvm: 2.2
      env: TASK=mutant
    - rvm: 2.2
      env: TASK=rubocop
